### ISSUE TITLE
Storm Prediction Center Alerts

### ISSUE THREAD

**Issue by pjrish** [finity69x2/nws_alerts#110]
Good morning,

Not sure if this could be added to future code or not, but I added some code to pull the SPC day 1 outlook, and report it to Home Assistant.

The following are needed for it to work in its current state:
- Install "pyscript" (HACS)
- manually add the following sensor to configuration.yaml
```
sensor:
  - platform: rest
    name: SPC GeoJSON
    resource: https://www.spc.noaa.gov/products/outlook/day1otlk_cat.lyr.geojson
    value_template: "{{ now().isoformat() }}"
    json_attributes:
      - features
```
- create a number helper: "input_number.spc_risk_level" (minimum 0, maximum 5, type: slider, step size: 1)

In your /pyscript/ folder create a file named "spc_geojson_check.py" and paste the following code:
- edit lines 3/4 with your lat/lon values
```
@service
def update_spc_risk():
    LAT = 45.0
    LON = -90.0
    HELPER = "input_number.spc_risk_level"

    SPC_RISK_MAP = {
        "TSTM": 0,
        "MRGL": 1,
        "SLGT": 2,
        "ENH": 3,
        "MOD": 4,
        "HIGH": 5
    }

    def point_in_poly(lat, lon, poly):
        inside = False
        j = len(poly) - 1
        for i in range(len(poly)):
            xi, yi = poly[i]
            xj, yj = poly[j]
            if ((yi > lat) != (yj > lat)) and \
               (lon < (xj - xi) * (lat - yi) / ((yj - yi) + 1e-10) + xi):
                inside = not inside
            j = i
        return inside

    features = state.get("sensor.spc_geojson.features")

    if features is None:
        log.error("[SPC] No features found in sensor.spc_geojson")
        return

    max_level = 0

    for feature in features:
        label = feature["properties"].get("LABEL", "")
        level = SPC_RISK_MAP.get(label, 0)

        coords = feature["geometry"].get("coordinates", [])
        if feature["geometry"]["type"] == "Polygon":
            polygons = [coords]
        elif feature["geometry"]["type"] == "MultiPolygon":
            polygons = coords
        else:
            continue

        for poly in polygons:
            if point_in_poly(LAT, LON, poly[0]):
                max_level = max(max_level, level)
                break

    state.set(HELPER, max_level)
    log.info(f"[SPC] Risk level set to {max_level}")
```

I run an automation every 3 hours to pull and parse the forecast:
```
alias: Update Storm Prediction Center Risk
description: ""
triggers:
  - trigger: time_pattern
    hours: /3
    minutes: "05"
conditions: []
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.spc_geojson
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - action: pyscript.update_spc_risk
    data: {}
mode: single
```

The following conditional markdown card is on my dashboard for both the SPC and Weather Warnings:
```
type: conditional
conditions:
  - condition: or
    conditions:
      - condition: state
        entity: sensor.nws_alerts_alerts
        state_not: "0"
      - condition: state
        entity: input_number.spc_risk_level
        state_not: "0"
card:
  type: markdown
  content: >-
    {% set alerts = state_attr('sensor.nws_alerts_alerts', 'Alerts') |
    default([]) %} {% set priority_order = ['Tornado Warning', 'Severe
    Thunderstorm Warning', 'Flash Flood Warning',
                             'Tornado Watch', 'Severe Thunderstorm Watch', 'Flood Watch'] %}

    # ⚠️ WEATHER ALERTS ⚠️


    {% set spc_risk = states('input_number.spc_risk_level') | int %}

    {% set spc_labels = ['General Thunderstorms', 'Marginal', 'Slight',
    'Enhanced', 'Moderate', 'High'] %}

    {% if spc_risk > 0 %}

    # Today's SPC Risk: *{{spc_labels[spc_risk] }} ({{ spc_risk }}/5)* #


    ---

    {% endif %}


    {% macro render_alert(alert) %}
      {% set expires = as_timestamp(alert.Expires) if alert.Expires else 0 %}
      {% set ends = as_timestamp(alert.Ends) if alert.Ends else 0 %}
      {% set relevant_time = expires if expires > ends else ends %}
      {% set label = 'Expires' if expires >= ends else 'Ends' %}
      {% set time_remaining = relevant_time - as_timestamp(now()) %}
      {% set days = (time_remaining // 86400) | int %}
      {% set hours = (time_remaining % 86400) // 3600 %}
      {% set minutes = (time_remaining % 3600) // 60 %}
      {% set formatted_time = relevant_time | timestamp_custom('%-d %B @ %H:%M Local', true) %}

      ---
      {% if time_remaining > 0 %}
      ## **{{ alert.Event }}:** _({{ '%02d' % hours }}:{{ '%02d' % minutes }} Remaining)_
      > _({{ label }}: {{ formatted_time }})_
      {% else %}
      ## **{{ alert.Event }}**
      > _EXPIRED_
      {% endif %}
      
      {% if "Special" in alert.Event and alert.Description %}
      {{ alert.Description | replace('\n\n', '\n') }}
      {% endif %}
    {% endmacro %}

    {% for event_type in priority_order %}
      {% set matched = alerts | selectattr('Event', 'equalto', event_type) | list %}
      {% if matched %}
        {% set most_recent = matched | sort(attribute='Expires', reverse=True) | first %}
        {{ render_alert(most_recent) }}
      {% endif %}
    {% endfor %}

    {% set others = alerts | rejectattr('Event', 'in', priority_order) | list %}
    {% for alert in others %}
      {{ render_alert(alert) }}
    {% endfor %}
  text_only: true
```

Example display:

<img width="454" alt="Image" src="https://github.com/user-attachments/assets/f468c208-6496-4754-b55c-bc970ec5d541" />
