### ISSUE TITLE
V5 - Only 1 Attribute

### ISSUE THREAD

**Issue by j6s33m** [finity69x2/nws_alerts#85]
Is there a reason why in v5, you removed all the individual attributes and lumped all the content into a single attribute? I read and understand that you called out breaking changes in your update notes, but what I fail to understand is how this is better? Do you have new automation examples or dashboard examples of how this is easier/better to use?  At first glance, this feels like a significant downgrade in experience. 

Please help me understand how I should look at this differently. 

Thanks

**Comment by j6s33m** [comment]
Those will not as there is only one attribute now with all the data in it. So no way to trigger based on all the prior attributes. 

I downgraded for now, but am still curious as to why the change was made. Hoping we get a better explanation.

**Comment by ruchoff** [comment]
You can still pull the different elements of the attribute by indexing into the attribute:

`{{ state_attr('sensor.nws_alerts', 'Alerts')[0]['Event'] }}`

The above is taking the first alert in the Alerts list, `[0]`, then indexing for the value of the key `Event` for that first alert. I was able to update all my cards with this syntax and have had no issues.

**Comment by T3chArmy** [comment]
@wormuths I made some new automations for V5 check #87 to see if they fit the bill for your use cases.

**Comment by T3chArmy** [comment]
@j6s33m @wormuths I made some new automations for V5 check #87 to see if they fit the bill for your use cases.

**Comment by inguy24** [comment]
If I am interpreting things correctly, it sounds like the parsing of the data now falls to me in my automations? Is that correct? If so, do you have an example of what the output could look like in V5 so i would know how to construct a query? I was able to piece together what to expect in each of the attributes in your previous version, but now am a bit mystified as to what is actually being delivered through your integration.

**Comment by j6s33m** [comment]
> If I am interpreting things correctly, it sounds like the parsing of the data now falls to me in my automations? Is that correct? If so, do you have an example of what the output could look like in V5 so i would know how to construct a query? I was able to piece together what to expect in each of the attributes in your previous version, but now am a bit mystified as to what is actually being delivered through your integration.

@T3chArmy posed above how to write automations and get the information. Took some getting used to, but I appreciate the examples. I'm sure there is a reason why the owner made this move...still not sure, but I can adjust.

**Comment by T3chArmy** [comment]
@j6s33m

To me, this new format is much easier to work with. It's a lot easier to get the information out of the integration. 

Instead of having to split everything at - and hope you're getting the right info.

Now you can loop through the JSON object and know you're getting the relevant info.

Basically the only thing that has changed is the order in which you access the data, and you no longer have to manually split every attribute.

There is a bit of a learning curve, but I agree with the changes the dev has made on this integration. Much better handling of information to make it easier to process.

**Comment by inguy24** [comment]
> > If I am interpreting things correctly, it sounds like the parsing of the data now falls to me in my automations? Is that correct? If so, do you have an example of what the output could look like in V5 so i would know how to construct a query? I was able to piece together what to expect in each of the attributes in your previous version, but now am a bit mystified as to what is actually being delivered through your integration.
> 
> @T3chArmy posed above how to write automations and get the information. Took some getting used to, but I appreciate the examples. I'm sure there is a reason why the owner made this move...still not sure, but I can adjust.

I disagree with you there. I went through his automations, but I don't like those automations and prefer to keep all of my automations in Node Red. Those automations do not address any of my needs and do not make it clear what the data set looks like that the author's integration is providing. This is just poor programming and poor documentation. 

You are right that it is the author's own right to trash his own work. But in terms of inferring I cannot read, please keep that to yourself.  I guess it is time for a fork. HACS is pretty strict in terms of things being documented correctly. As the author has not replied as to even providing information on what a dataset looks like that comes from his work, and considering his work is based upon TIMELY and CORRECT alerts to weather phenomena that could be a threat to life and property, I would expect more from the author in terms of their responsibility to the data. and his/her users.

**Comment by rct** [comment]
First, this new release was pretty clearly labeled as a breaking change with a new major release number. 

Second, I suggest trying to understand the NWS Alerts API and the various edge conditions. It doesn't seem to be well documented to me. It is an evolution of a very old text based service that was designed in the days of the teletype. 

Third, Home Assistant has been going through its own breaking changes with regards to weather forecasts, textual data, the use (and over use?) of attributes with an eye towards improving efficiency and performance. 

I feel taking it upon yourself to request that someone else's work be removed from HACS is quite offensive. Particularly so because this is a _custom integration_ that someone decided to write and make available _without any compensation_.

**Comment by T3chArmy** [comment]
@wormuths I would be happy to lend a hand with updating your automations. Looks like the changes on most of these should be pretty straight forward. 

For most of yours you could simply replace your instances of

`state_attr('sensor.nws_alerts', 'title').split('-')[0]` with `(state_attr(sensor.nws_alerts', 'Alerts') | map(attribute='Headline'))[0]`

There are likely other ways to accomplish this same thing with less code, but that's what immediately comes to mind.

**Comment by T3chArmy** [comment]
@wormuths my evening is pretty busy tonight and tomorrow,but I should have time Saturday to take a deep dive into your automation if someone doesn't beat me to it.

In the mean time I'd keep running v4.4 until then.

**Comment by finity69x2** [comment]
there are some pretty harsh comments here. especially the one who actually requested my work be removed from HACS. That's pretty crappy so @inguy24 won't be getting any direct help from me on anything further.

For the others, I usually don't interact with users in the issues section here and I prefer to use the HA Forum for this type of thing so if any of you would like to start a thread there I would be more than happy to help you there. Just tag me in the thread. Or even better is just add to the existing thread dedicated to the integration found at https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853

To answer some of the questions...

I hate breaking changes. I really really do. But the way the old integration attributes were laid out was horrendous. the new layout is completely inline with pretty much every single entity that has lists of attributes. The old way was very cumbersome to template and was pretty much completely non-readable for a person. So after a long deliberation I decided to update the integration. 

@j6s33m You are not correct that all the data is in one attribute. There is one "Alert" attribute that contains a list of all the current alerts. Each of those alerts contain exactly the same data that the old integration gave you.

The layout is:

```
Alerts:
  - alert 1 
  - alert 2
  - etc
```

So example to see the event for the first alert in the list the way the data is accessed is 

```
{{state_attr('sensor.nws_alerts', 'Alerts')[0].Event}}
```

to find the description for the third alert:

```
{{state_attr('sensor.nws_alerts', 'Alerts')[2].Description}}
```

all of that is the standard way to template any dictionary of attributes anywhere in HA. And you will notice there are no more cumbersome "splits", "/n", etc anymore.

Then, before releasing the update, I spent several weeks developing example automations and dashboard code to almost replicate the old functionality using the new attribute layout. I think that any changes that are there only make the automations more reliable. I know that not all users are coders and that's why I provide you with a pretty much turn-key package to use out of the box. I can't be held completely responsible for how every individual user ever uses the integration but I try my best to help as much as I can.

Did any of you who are complaining that the old automations won't actually read the readme where I stated that the package and dashboard code examples had been updated to work with the new layout? Did you actually then look at the example code contained there?

Again any of you that would like more in-depth help can start a thread on the HA forum.

But particularly @wormuths...

let's deal with the easiest first - your dashboard card. I'm pretty sure that card is taken directly from my old dashboard example. The updated dashboard example is in the "dashboard" folder in the repo. just replace everything you have now with that code and it should just work. And the improvement is that the old card was limited to just the first 5 alerts. the new card will show all alerts no matter how many there are.

as to you other automations those are a bit more complex to convert but there are many examples given in the package folder as well.

here is the first:

```
alias: Household - Climate (Severe Weather Mode) Tornado Warning - Activate
description: ""
trigger:
  - platform: state
    entity_id: sensor.nws_alerts
condition:
  - condition: template
    value_template: >
      {% set ns = namespace(events=[]) %}
      {% for x in range(0,states('sensor.nws_alerts_test')|int ) %}
        {% set event = state_attr('sensor.nws_alerts_test', 'Alerts')[x].Event %}
        {% set ns.events = ns.events + [event] %}
     {% endfor -%}
     {{ 'Tornado Warning' in ns.events  }}
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.severe_weather
    alias: Activate Severe Weather Mode
  - alias: Activate Severe Weather Mode (Tornado Warning)
    service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
        - input_boolean.severe_weather_tornado_warning
  - alias: Notify Living Room (LG WebOS Television)
    service: notify.lg_television_wifi_living_room
    data:
      message: The National Weather Service has issued/updated a Tornado Warning.
mode: single
```

it looks at the state of the sensor (and yes the state still gives the count of alerts just like the old version. the only thing changed in the new version is the way the attributes are laid out.) and then checks if any of the alerts are a tornado warning. if yes then the actions are run.

then the second:

```
alias: Household - Climate (Severe Weather Mode) Tornado Warning - Deactivate
description: ""
trigger:
  - platform: state
    entity_id: sensor.nws_alerts
condition:
  - condition: template
    value_template: >
      {% set ns = namespace(events=[]) %}
      {% for x in range(0,states('sensor.nws_alerts_test')|int ) %}
        {% set event = state_attr('sensor.nws_alerts_test', 'Alerts')[x].Event %}
        {% set ns.events = ns.events + [event] %}
     {% endfor -%}
     {{ 'Tornado Warning' not in ns.events  }}
action:
  - alias: Deactivate Severe Weather Mode (Tornado Warning)
    service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
        - input_boolean.severe_weather_tornado_warning
mode: single
```

Again it looks at the state of the sensor and then checks that none of the alerts are a tornado warning. if not then the actions are run.

I haven't fully 100% tested them but in my limited tests (I don't have a tornado warning right now thankfully) I'm fairly confident they will work.

If there is some question then please post in the HA forum for further help.

and to @T3chArmy and @rct thank you for your support.
